export type Resource = {
  number: string;
  slug: string;
  title: string;
  description: string;
  audience: "families" | "patients" | "clinical" | "managers";
  audienceLabel: string;
  pages: number;
  tone: "coral" | "blue" | "lime" | "violet";
  featured?: boolean;
  studentRecommended?: boolean;
  keywords?: string;
};

export const resources: Resource[] = [
  {
    number: "01",
    slug: "what-is-delirium",
    title: "What is delirium?",
    description: "A plain-language handout explaining sudden confusion, common signs and why prompt assessment matters.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "coral",
    featured: true,
  },
  {
    number: "02",
    slug: "signs-and-urgent-action",
    title: "Signs to notice - and what to do now",
    description: "A handout for discussing what a family should do about a sudden change in thinking or behaviour.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "lime",
    featured: true,
  },
  {
    number: "03",
    slug: "finding-triggers-family",
    title: "Finding the triggers of delirium",
    description: "A handout explaining what the team may look for and the information families can provide.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "blue",
  },
  {
    number: "04",
    slug: "how-delirium-is-treated",
    title: "How delirium is treated",
    description: "A handout for explaining treatment across causes, body function, comfort and recovery.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "violet",
    featured: true,
  },
  {
    number: "05",
    slug: "preventing-delirium",
    title: "Helping to prevent delirium",
    description: "A handout on practical steps supporting orientation, sleep, movement, intake and sensory needs.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "lime",
  },
  {
    number: "06",
    slug: "family-help-at-bedside",
    title: "How families can help at the bedside",
    description: "A bedside handout on small, calm actions that can make care less confusing or frightening.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "coral",
  },
  {
    number: "07",
    slug: "delirium-or-dementia",
    title: "Delirium or dementia?",
    description: "An at-a-glance handout, including why sudden change still needs urgent assessment.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "blue",
  },
  {
    number: "08",
    slug: "what-to-say-to-staff",
    title: "What to say to the clinical team",
    description: "A family handout with useful words for describing rapid change and raising concerns.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "violet",
  },
  {
    number: "09",
    slug: "after-delirium",
    title: "After delirium",
    description: "A take-home handout on recovery, what to record and when to seek further advice.",
    audience: "patients",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "blue",
  },
  {
    number: "10",
    slug: "frightening-beliefs-and-hallucinations",
    title: "Frightening beliefs or hallucinations",
    description: "A handout on responding without arguing, reducing distress and sharing information with staff.",
    audience: "families",
    audienceLabel: "Patient & family handout",
    pages: 1,
    tone: "coral",
  },
  {
    number: "11",
    slug: "recognising-delirium-at-the-bedside",
    title: "Recognising delirium at the bedside",
    description: "A compact prompt to establish baseline and assess arousal, attention and acute change.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "blue",
    featured: true,
    studentRecommended: true,
    keywords: "hypoactive quiet drowsy withdrawn reduced arousal acute change fluctuation",
  },
  {
    number: "12",
    slug: "positive-4at-next-steps",
    title: "A positive 4AT: what happens next?",
    description: "The assessment, communication and care actions that should follow a positive screen.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "lime",
    studentRecommended: true,
    keywords: "screen assessment diagnosis clinical judgement score",
  },
  {
    number: "13",
    slug: "structured-cause-sweep",
    title: "Finding triggers: a structured cause sweep",
    description: "A systematic, patient-specific prompt for urgent threats and multiple concurrent causes.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "coral",
    featured: true,
    studentRecommended: true,
    keywords: "triggers causes precipitants investigation acute illness",
  },
  {
    number: "14",
    slug: "daily-multidomain-review",
    title: "The daily multidomain delirium review",
    description: "A ward-round structure for reviewing causes, physiology, medicines, function and distress together.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "violet",
    featured: true,
    studentRecommended: true,
    keywords: "multidomain treatment physiology recovery ward round",
  },
  {
    number: "15",
    slug: "shift-by-shift-non-drug-care",
    title: "Non-drug care: shift by shift",
    description: "A nursing and support-worker checklist for needs that can change across every shift.",
    audience: "clinical",
    audienceLabel: "Nurses & care staff",
    pages: 1,
    tone: "blue",
    keywords: "hypoactive quiet drowsy nursing HCA food fluids intake",
  },
  {
    number: "16",
    slug: "agitation-or-unmet-need",
    title: "Agitation or unmet need?",
    description: "A two-minute needs sweep before escalation, with de-escalation and safety prompts.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "coral",
    keywords: "hallucination fear distress de-escalation",
  },
  {
    number: "17",
    slug: "preventing-delirium-clinical",
    title: "Preventing delirium from admission",
    description: "A tailored multicomponent approach for people at risk, linked to named actions and review.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "lime",
  },
  {
    number: "18",
    slug: "delirium-discharge-summary",
    title: "Five essentials for the discharge summary",
    description: "A practical prompt for diagnosis, course, causes, medicine changes and follow-up needs.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "violet",
  },
  {
    number: "19",
    slug: "multidomain-treatment",
    title: "Multidomain treatment of delirium",
    description: "A whole-person treatment structure joining cause-directed care, physiology, function, distress and review.",
    audience: "clinical",
    audienceLabel: "Clinical teams",
    pages: 1,
    tone: "coral",
    featured: true,
    studentRecommended: true,
    keywords: "treatment multidomain causes physiology brain recovery complications",
  },
  {
    number: "20",
    slug: "hypoactive-delirium",
    title: "Hypoactive delirium: the quiet change",
    description: "Recognition and response prompts for drowsiness, withdrawal, reduced movement and poor engagement.",
    audience: "clinical",
    audienceLabel: "Health & care staff",
    pages: 1,
    tone: "blue",
    featured: true,
    studentRecommended: true,
    keywords: "hypoactive quiet drowsy withdrawn sleepy reduced arousal depression passive",
  },
  {
    number: "21",
    slug: "medicines-and-delirium",
    title: "Medicines and delirium",
    description: "A safety-focused review prompt covering medicine changes, withdrawal, prescribing and stop plans.",
    audience: "clinical",
    audienceLabel: "Prescribers & pharmacists",
    pages: 1,
    tone: "lime",
    studentRecommended: true,
    keywords: "pharmacy medication antipsychotic haloperidol withdrawal ECG QT Parkinson Lewy body",
  },
  {
    number: "22",
    slug: "allied-health-function-recovery",
    title: "Allied health, function and recovery",
    description: "A practical prompt for baseline function, safe activity, participation, rehabilitation and transitions.",
    audience: "clinical",
    audienceLabel: "Allied health professionals",
    pages: 1,
    tone: "violet",
    keywords: "AHP physiotherapy occupational therapy speech language dietetics mobility rehabilitation recovery function",
  },
  {
    number: "23",
    slug: "care-home-community-response",
    title: "Care-home and community response",
    description: "What to notice, record, hand over and do when a new change develops outside hospital.",
    audience: "clinical",
    audienceLabel: "Community & care-home teams",
    pages: 1,
    tone: "coral",
    keywords: "care home community primary care ambulance escalation transfer care at home",
  },
  {
    number: "24",
    slug: "delirium-sensitive-hospital",
    title: "Is your hospital delirium-sensitive?",
    description: "Eight leadership questions covering recognition, response, family partnership and recovery.",
    audience: "managers",
    audienceLabel: "Managers & leaders",
    pages: 1,
    tone: "violet",
  },
  {
    number: "25",
    slug: "audit-delirium-detection",
    title: "Audit your delirium detection system",
    description: "A measurement guide that looks beyond completion rates to cases found and action taken.",
    audience: "managers",
    audienceLabel: "QI & service managers",
    pages: 1,
    tone: "lime",
  },
];
